# Generated by Django 4.2.20 on 2025-03-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_attendance_created_at_attendance_present_and_more'),
        ('Home', '0007_update_attendance_model'),
    ]

    operations = [
    ]
