# Generated by Django 4.2.20 on 2025-03-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_merge_20250327_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='Home.student'),
        ),
    ]
